name: ofbuild

on: [push, pull_request]
jobs:
  build_version:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]
        # os: [ubuntu-latest] ,

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: brew
        shell: bash
        run: brew install yaml-cpp fmt 
        # pkg-config 

      - name: compile
        shell: bash
        run: g++ -std=c++17 `pkg-config --libs --cflags fmt yaml-cpp` src/main.cpp -o ofbuild -O3

      - name: zip
        shell: bash
        run: zip ofbuild.zip ofbuild

      - name: LS
        shell: bash
        run: |
          # ls -alFR
          ls -alF

      # - name: Update Release
      #   uses: johnwbyrd/update-release@v1.0.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: nightly
      #     release: nightly
      #     prerelease: false
      #     files: ofbuild.zip

      - name: "Upload assets"
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./ofbuild.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          # token: ${{ secrets.pat }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false

          
