name: OFBUILD

on: [push, pull_request]
jobs:
  build_version:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]
        # os: [ubuntu-latest] ,

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: brew
        shell: bash
        run: brew install brew install pkg-config yaml-cpp fmt

      - name: compile
        shell: bash
        run: g++ -std=c++17 `pkg-config --libs --cflags fmt yaml-cpp` src/main.cpp -o ofbuild -O3

      - name: zip
        shell: bash
        run: zip ofbuild.zip ofbuild

      - name: LS
        shell: bash
        run: |
          ls -alFR

      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          release: nightly
          prerelease: false
          files: ofbuild.zip

